[package]
name = "my_app"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive"] }
crossbeam-channel = "0.5.15"
rdev = "0.5"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
